services:
  - type: web
    name: 0bullshit-testing-interface
    env: python
    buildCommand: pip install -r testing_interface/requirements.txt
    startCommand: cd testing_interface && python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8001
      - key: DEBUG
        value: false
    autoDeploy: false